version: '3.8'

services:
  novel-app:
    image: mattgideon/freenovel:v1.0.11-prod
    container_name: novel-app
    ports:
      - "${SERVER_PORT:-8081}:8081"
    environment:
      # 应用配置
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      
      # Sitemap 配置
      SITEMAP_RUN: ${SITEMAP_RUN:-false}
      
      # 代理配置
      PROXY_HOST: ${PROXY_HOST:-}
      PROXY_PORT: ${PROXY_PORT:-7897}
      PROXY_CLIENT: ${PROXY_CLIENT:-false}

      # 定时任务控制配置
      TASK_SCHEDULER_ENABLED: ${TASK_SCHEDULER_ENABLED:-false}
      
      # 连续失败多少次后自动禁用任务
      TASK_FAILURE_THRESHOLD: ${TASK_FAILURE_THRESHOLD:-3}
      # 任务禁用后多少分钟自动恢复
      TASK_FAILURE_RESET_MINUTES: ${TASK_FAILURE_RESET_MINUTES:-60}
      
      # Novelpia相关任务
      TASK_NOVELPIA_TASK2_ENABLED: ${TASK_NOVELPIA_TASK2_ENABLED:-true}
      TASK_NOVELPIA_PHOTO_ENABLED: ${TASK_NOVELPIA_PHOTO_ENABLED:-true}
      TASK_NOVELPIA_UPLOAD_TRANSLATION_ENABLED: ${TASK_NOVELPIA_UPLOAD_TRANSLATION_ENABLED:-false}
      TASK_NOVELPIA_UPLOAD_TRANSLATION_EXCEPTION_ENABLED: ${TASK_NOVELPIA_UPLOAD_TRANSLATION_EXCEPTION_ENABLED:-false}
      TASK_NOVELPIA_TASK3_ENABLED: ${TASK_NOVELPIA_TASK3_ENABLED:-true}
      TASK_NOVELPIA_FIX_ERROR_CHAPTER_ENABLED: ${TASK_NOVELPIA_FIX_ERROR_CHAPTER_ENABLED:-true}
      
      # Sitemap生成任务
      TASK_SITEMAP_HTML_GENERATOR_ENABLED: ${TASK_SITEMAP_HTML_GENERATOR_ENABLED:-true}
      TASK_SITEMAP_INDEX_GENERATOR_ENABLED: ${TASK_SITEMAP_INDEX_GENERATOR_ENABLED:-true}
      
      # Novelpia爬虫任务
      TASK_NOVELPIA_CRAWLER_ENABLED: ${TASK_NOVELPIA_CRAWLER_ENABLED:-true}
      
      # 从文件更新小说数据任务
      TASK_UPDATE_NOVEL_FROM_FILE_ENABLED: ${TASK_UPDATE_NOVEL_FROM_FILE_ENABLED:-true}
      
      # Cloudflare R2 配置
      CLOUDFLARE_R2_ACCOUNT_ID: ${CLOUDFLARE_R2_ACCOUNT_ID:-}
      CLOUDFLARE_R2_ACCESS_KEY: ${CLOUDFLARE_R2_ACCESS_KEY:-}
      CLOUDFLARE_R2_SECRET_KEY: ${CLOUDFLARE_R2_SECRET_KEY:-}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME:-photo}
      CLOUDFLARE_R2_REGION: ${CLOUDFLARE_R2_REGION:-auto}
      CLOUDFLARE_R2_ENABLED: ${CLOUDFLARE_R2_ENABLED:-true}
      
      # 文件上传目录
      FILE_UPLOAD_TEMP_DIR: /app/tmp/
      FILE_UPLOAD_STORAGE_DIR: /app/file/

      # 日记目录
      LOG_FILE_PATH: /app/logs/
      
      # 单数据库模式
      DATABASE_MODE: single
      
      # 主数据库配置
      PRIMARY_DB_URL: ${PRIMARY_DB_URL}
      PRIMARY_DB_USERNAME: ${PRIMARY_DB_USERNAME}
      PRIMARY_DB_PASSWORD: ${PRIMARY_DB_PASSWORD}
      PRIMARY_DB_POOL_SIZE: ${PRIMARY_DB_POOL_SIZE:-15}
      PRIMARY_DB_MIN_IDLE: ${PRIMARY_DB_MIN_IDLE:-5}
    volumes:
      - ./app/tmp:/app/tmp
      - ./app/file:/app/file
      - ./app/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - novel-network

networks:
  novel-network:
    driver: bridge
